name: bimanual-teleop
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - tk
  - pip:
      - numpy==1.26.4
      - matplotlib==3.10.9
      - -e .[visualization,wuji,realsense]
variables:
  PIP_USER: "false"
  PYTHONNOUSERSITE: "1"
